on:
  push:
    branches: [main]
    paths:
      - 'seaplane-cli/src/**/*.rs'
      - 'seaplane-cli/build.rs'
      - 'seaplane-cli/Cargo.toml'
      - 'seaplane-cli/share/third_party_licenses.md'
      - 'LICENSE'
  workflow_dispatch:

name: Nightly Seaplane CLI Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-win-x64:
    uses: ./.github/workflows/workflow-build-release.yml
    with:
      runner: "['windows-latest']"
      use-short-sha: true

  build-linux-x64-gnu:
    uses: ./.github/workflows/workflow-build-release.yml
    with:
      runner: 'buildjet-4vcpu-ubuntu-2204'
      use-short-sha: true

  build-linux-aarch64-gnu:
    uses: ./.github/workflows/workflow-build-release.yml
    with:
      runner: 'buildjet-8vcpu-ubuntu-2204-arm'
      use-short-sha: true

  # Currently we build by hand to sign and notarize the builds
  # build-mac-x64:
  #   uses: ./.github/workflows/workflow-build-release.yml
  #   with:
  #     runner: "['macos-latest']"
  #     use-short-sha: true

  release:
    name: Nightly Release
    runs-on: buildjet-4vcpu-ubuntu-2204
    needs:
      - build-win-x64
      - build-linux-x64-gnu
      - build-linux-aarch64-gnu
        #- build-mac-x64
    steps:
      - name: Remove previous Nightly Release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: nightly
          repo: seaplane-io/seaplane
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha

      - name: Download all workflow release artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/

      - name: Create Nightly Release
        uses: softprops/action-gh-release@v1
        with:
          name: Seaplane CLI Nightly (${{ env.SHA }})
          tag_name: nightly
          prerelease: true
          files: |
            artifacts/artifact/seaplane-*.tar.gz
            artifacts/artifact/seaplane-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: seaplane-io/seaplane
          SHA: ${{ steps.short-sha.outputs.sha }}
